import type { Metadata } from "next";
import ThemeToggle from "@/components/client/ThemeToggle";
import localFont from "next/font/local";
import "./globals.css";
import Logo from "@/components/client/Logo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {/* header加入下划线阴影 */}
        <header className="flex items-center justify-between w-full px-3 py-2 border-b border-gray-200 dark:border-gray-800">
          <Logo />
          <div className="ml-auto">
            <ThemeToggle />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
